version: '3.8'

services:
  web:
    build: .
    container_name: web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - celery_worker

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - rabbitmq

  flower:
    build: .
    container_name: flower
    command: celery -A app.tasks flower --port=5555 --broker=amqp://rabbitmq:5672//
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
